package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"fmt"

	"github.com/obutora/go_graphql_template/generated/ent"
	"github.com/obutora/go_graphql_template/graph/generated"
)

// CreateDot is the resolver for the createDot field.
func (r *mutationResolver) CreateDot(ctx context.Context, title string) (*ent.Dot, error) {
	panic(fmt.Errorf("not implemented: CreateDot - createDot"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
